#!/bin/bash
# Script de Otimização e Setup para o Site

echo "🚀 Iniciando setup do site com animações profissionais..."
echo ""

# 1. Verificar estrutura
echo "📁 Estrutura de arquivos:"
echo "✅ /Web/styles/main.css"
echo "✅ /Web/styles/responsive.css" 
echo "✅ /Web/styles/animations.css"
echo "✅ /Web/js/animations.js"
echo "✅ /Web/index.html"
echo "✅ /Web/guide.html"
echo "✅ /Web/portfolio-advanced.html"
echo ""

# 2. Instruções para servidor local
echo "🌐 Para testar localmente:"
echo ""
echo "Opção 1 - Python 3:"
echo "  cd 'Web'"
echo "  python -m http.server 8000"
echo ""
echo "Opção 2 - Python 2:"
echo "  cd 'Web'"
echo "  python -m SimpleHTTPServer 8000"
echo ""
echo "Opção 3 - Node.js:"
echo "  npm install -g http-server"
echo "  cd 'Web'"
echo "  http-server -p 8000"
echo ""
echo "Opção 4 - VS Code Live Server:"
echo "  Instale extensão 'Live Server'"
echo "  Clique direito em index.html > 'Open with Live Server'"
echo ""

# 3. Checklist de GIFs
echo "🎬 Próximos Passos - Integrar GIFs:"
echo ""
echo "1️⃣  Hero Section (💻):"
echo "    Busque em GIPHY: 'coding animation', 'terminal typing'"
echo "    Substitua em index.html linha ~30"
echo ""
echo "2️⃣  About Section (🚀):"
echo "    Busque: 'rocket launch', 'startup animation'"
echo "    Substitua em index.html linha ~50"
echo ""
echo "3️⃣  Projects Section (⚙️):"
echo "    Busque: 'gears rotating', 'dev tools animation'"
echo "    Substitua em index.html linha ~70"
echo ""
echo "4️⃣  Experience Section (📊):"
echo "    Busque: 'animated dashboard', 'data visualization'"
echo "    Substitua em index.html linha ~100"
echo ""
echo "5️⃣  Contact Section (📧):"
echo "    Busque: 'email animation', 'message sending'"
echo "    Substitua em index.html linha ~120"
echo ""

# 4. Otimização de performance
echo "⚡ Dicas de Otimização:"
echo ""
echo "1. Use EZGIF para comprimir GIFs (https://ezgif.com/optimize)"
echo "2. Tamanho máximo por GIF: 3MB"
echo "3. Dimensão recomendada: 300-600px de largura"
echo "4. Reduza frames: 15-20 frames por segundo"
echo "5. Considere WebP para melhor compressão"
echo ""

# 5. Testes
echo "✅ Checklist de Testes:"
echo ""
echo "Desktop (1920x1080):"
echo "  ☐ Todas as animações visíveis"
echo "  ☐ Sem lag ou stutter"
echo "  ☐ GIFs carregam em < 3s"
echo ""
echo "Tablet (768x1024):"
echo "  ☐ Layout responsivo"
echo "  ☐ Menu hamburger funcional"
echo "  ☐ Emojis/GIFs bem posicionados"
echo ""
echo "Mobile (375x667):"
echo "  ☐ Tudo visível sem scroll horizontal"
echo "  ☐ Botões clicáveis"
echo "  ☐ Animações suave"
echo ""

# 6. Ferramentas recomendadas
echo "🛠️  Ferramentas Recomendadas:"
echo ""
echo "Encontrar GIFs:"
echo "  • GIPHY: https://giphy.com"
echo "  • Tenor: https://tenor.com"
echo "  • Pixabay: https://pixabay.com"
echo ""
echo "Editar/Otimizar:"
echo "  • EZGIF: https://ezgif.com"
echo "  • Photopea: https://photopea.com"
echo "  • FFmpeg: https://ffmpeg.org"
echo ""
echo "Testar Performance:"
echo "  • PageSpeed: https://pagespeed.web.dev"
echo "  • GTmetrix: https://gtmetrix.com"
echo "  • WebPageTest: https://webpagetest.org"
echo ""

# 7. Documentação
echo "📚 Documentação:"
echo ""
echo "Abra em seu navegador:"
echo "  • http://localhost:8000/guide.html"
echo "  • http://localhost:8000/portfolio-advanced.html"
echo ""
echo "Leia em editor de texto:"
echo "  • ANIMATIONS_README.md"
echo "  • IMPLEMENTATION_SUMMARY.md"
echo ""

echo ""
echo "✨ Setup completo! Comece a explorar suas animações! 🚀"
